In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv("cardata.csv")

In [12]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [13]:
df.shape

(301, 9)

In [15]:
df["Car_Name"].value_counts()

Car_Name
city                        26
corolla altis               16
verna                       14
fortuner                    11
brio                        10
                            ..
Honda CB Trigger             1
Yamaha FZ S                  1
Bajaj Pulsar 135 LS          1
Activa 4g                    1
Bajaj Avenger Street 220     1
Name: count, Length: 98, dtype: int64

In [19]:
#check the total brand
df["Car_Name"].nunique()

98

In [22]:
df["Fuel_Type"].value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

### 1. OneHotEncoding using Panada

In [24]:
pd.get_dummies(df,columns=["Fuel_Type","Seller_Type"])

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Transmission,Owner,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual
0,ritz,2014,3.35,5.59,27000,Manual,0,False,False,True,True,False
1,sx4,2013,4.75,9.54,43000,Manual,0,False,True,False,True,False
2,ciaz,2017,7.25,9.85,6900,Manual,0,False,False,True,True,False
3,wagon r,2011,2.85,4.15,5200,Manual,0,False,False,True,True,False
4,swift,2014,4.60,6.87,42450,Manual,0,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Manual,0,False,True,False,True,False
297,brio,2015,4.00,5.90,60000,Manual,0,False,False,True,True,False
298,city,2009,3.35,11.00,87934,Manual,0,False,False,True,True,False
299,city,2017,11.50,12.50,9000,Manual,0,False,True,False,True,False
300,brio,2016,5.30,5.90,5464,Manual,0,False,False,True,True,False

### 2. K-1 OneHotEncoding

In [26]:
pd.get_dummies(df,columns=["Fuel_Type","Seller_Type"],drop_first=True)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Transmission,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual
0,ritz,2014,3.35,5.59,27000,Manual,0,False,True,False
1,sx4,2013,4.75,9.54,43000,Manual,0,True,False,False
2,ciaz,2017,7.25,9.85,6900,Manual,0,False,True,False
3,wagon r,2011,2.85,4.15,5200,Manual,0,False,True,False
4,swift,2014,4.60,6.87,42450,Manual,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Manual,0,True,False,False
297,brio,2015,4.00,5.90,60000,Manual,0,False,True,False
298,city,2009,3.35,11.00,87934,Manual,0,False,True,False
299,city,2017,11.50,12.50,9000,Manual,0,True,False,False
300,brio,2016,5.30,5.90,5464,Manual,0,False,True,False

### 3. OneHotEncoding using Sckitlearn

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:8],df.iloc[:,-1],test_size=0.2,random_state=42)

In [55]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [56]:
from sklearn.preprocessing import OneHotEncoder

In [57]:
X_train.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission
184,Bajaj Pulsar 150,2008,0.25,0.750,26000,Petrol,Individual,Manual
132,Bajaj Avenger 220,2017,0.75,0.950,3500,Petrol,Individual,Manual
194,Hero CBZ Xtreme,2008,0.20,0.787,50000,Petrol,Individual,Manual
75,etios g,2015,3.95,6.800,36000,Petrol,Dealer,Manual
111,Royal Enfield Thunder 350,2016,1.15,1.500,8700,Petrol,Individual,Manual

In [58]:
ohe=OneHotEncoder()

In [59]:
ohe.fit_transform(X_train[["Fuel_Type","Seller_Type"]])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 480 stored elements and shape (240, 5)>

In [60]:
ohe.fit_transform(X_train[["Fuel_Type","Seller_Type"]]).toarray()

array([[0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       ...,
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.]], shape=(240, 5))

In [61]:
X_train_new=ohe.fit_transform(X_train[["Fuel_Type","Seller_Type"]]).toarray()

In [62]:
X_test_new=ohe.fit_transform(X_test[["Fuel_Type","Seller_Type"]]).toarray()

In [63]:
X_train[["Car_Name","Kms_Driven"]].values

array([['Bajaj Pulsar 150', 26000],
       ['Bajaj Avenger 220', 3500],
       ['Hero  CBZ Xtreme', 50000],
       ['etios g', 36000],
       ['Royal Enfield Thunder 350', 8700],
       ['fortuner', 41000],
       ['fortuner', 40000],
       ['ciaz', 18796],
       ['Hero Honda CBZ extreme', 75000],
       ['ritz', 51439],
       ['sx4', 50000],
       ['jazz', 28569],
       ['etios cross', 40534],
       ['eon', 23709],
       ['Mahindra Mojo XT300', 35000],
       ['Yamaha FZ S V 2.0', 5000],
       ['elantra', 12900],
       ['Bajaj  ct 100', 35000],
       ['city', 21780],
       ['brio', 14465],
       ['i20', 31604],
       ['innova', 197176],
       ['innova', 11000],
       ['i10', 53460],
       ['Activa 3g', 500],
       ['Royal Enfield Thunder 500', 5400],
       ['sx4', 41442],
       ['Hero Splender Plus', 50000],
       ['fortuner', 89000],
       ['Royal Enfield Classic 350', 17000],
       ['Suzuki Access 125', 1900],
       ['corolla altis', 56001],
       ['ertiga', 43000],
       ['alto 800', 2135],
       ['Activa 3g', 500000],
       ['city', 87934],
       ['corolla altis', 88000],
       ['grand i10', 24678],
       ['800', 127000],
       ['ertiga', 41678],
       ['Royal Enfield Classic 500', 40000],
       ['amaze', 44000],
       ['city', 69562],
       ['fortuner', 59000],
       ['i10', 22517],
       ['corolla altis', 12000],
       ['ritz', 54200],
       ['Honda Karizma', 30000],
       ['Bajaj Pulsar NS 200', 13000],
       ['jazz', 16002],
       ['Yamaha FZ  v 2.0', 25000],
       ['wagon r', 35500],
       ['Bajaj Discover 100', 21000],
       ['innova', 29000],
       ['eon', 11849],
       ['Bajaj Pulsar 220 F', 45000],
       ['land cruiser', 78000],
       ['creta', 35934],
       ['Yamaha FZ S V 2.0', 58000],
       ['city', 38000],
       ['city', 49562],
       ['Bajaj Avenger 220', 1300],
       ['Bajaj Avenger 220 dtsi', 16600],
       ['i20', 3435],
       ['corolla altis', 70000],
       ['Hero Extreme', 15000],
       ['TVS Wego', 22000],
       ['i20', 17000],
       ['alto k10', 10079],
       ['Honda CB twister', 33000],
       ['grand i10', 53000],
       ['grand i10', 21125],
       ['KTM 390 Duke ', 7000],
       ['Yamaha FZ S ', 5500],
       ['Royal Enfield Thunder 500', 14000],
       ['jazz', 4000],
       ['city', 27600],
       ['Yamaha FZ S V 2.0', 23000],
       ['TVS Jupyter', 19000],
       ['Hero Honda Passion Pro', 60000],
       ['ciaz', 6900],
       ['Royal Enfield Classic 350', 17500],
       ['verna', 36000],
       ['Honda Karizma', 213000],
       ['Bajaj Pulsar RS200', 5700],
       ['verna', 15001],
       ['brio', 5600],
       ['Bajaj Avenger 150', 7000],
       ['etios cross', 83000],
       ['ciaz', 45000],
       ['innova', 38000],
       ['verna', 71000],
       ['Royal Enfield Thunder 350', 15000],
       ['Honda Activa 4G', 4300],
       ['city', 9010],
       ['city', 54242],
       ['Hero Hunk', 49000],
       ['verna', 45078],
       ['etios liva', 45000],
       ['Bajaj Pulsar 150', 92233],
       ['camry', 142000],
       ['verna', 36100],
       ['Honda Activa 4G', 4000],
       ['ciaz', 15000],
       ['sx4', 49998],
       ['alto k10', 44542],
       ['Yamaha FZ  v 2.0', 29000],
       ['Hero  Ignitor Disc', 24000],
       ['Yamaha FZ 16', 18000],
       ['Bajaj Pulsar 135 LS', 13700],
       ['fortuner', 40000],
       ['corolla altis', 72000],
       ['i10', 35775],
       ['i20', 77632],
       ['alto k10', 46706],
       ['etios g', 40000],
       ['verna', 36000],
       ['Honda CBR 150', 23500],
       ['swift', 55138],
       ['amaze', 33019],
       ['Bajaj Avenger 150 street', 20000],
       ['grand i10', 28200],
       ['ritz', 27000],
       ['city', 18828],
       ['jazz', 61203],
       ['Royal Enfield Thunder 500', 3000],
       ['city', 29223],
       ['Bajaj Dominar 400', 1200],
       ['Hero Passion Pro', 6700],
       ['corolla altis', 45000],
       ['dzire', 48767],
       ['etios cross', 40588],
       ['TVS Apache RTR 180', 6000],
       ['verna', 60241],
       ['eon', 28282],
       ['verna', 49000],
       ['ciaz', 51000],
       ['brio', 60000],
       ['brio', 19000],
       ['swift', 16200],
       ['i20', 32000],
       ['swift', 42450],
       ['Royal Enfield Bullet 350', 6000],
       ['swift', 39000],
       ['xcent', 12479],
       ['Bajaj Pulsar NS 200', 14500],
       ['elantra', 43535],
       ['city', 25000],
       ['Honda CB Hornet 160R', 15000],
       ['fortuner', 78000],
       ['Bajaj Pulsar 150', 5000],
       ['Honda CB Hornet 160R', 3000],
       ['brio', 31427],
       ['ciaz', 20273],
       ['etios liva', 71000],
       ['jazz', 21200],
       ['fortuner', 6000],
       ['omni', 50000],
       ['creta', 68000],
       ['TVS Sport ', 15000],
       ['baleno', 24524],
       ['Royal Enfield Classic 350', 46500],
       ['brio', 9800],
       ['eon', 12500],
       ['Bajaj Pulsar NS 200', 45000],
       ['alto k10', 45280],
       ['amaze', 40023],
       ['KTM RC200', 6000],
       ['etios gd', 40000],
       ['grand i10', 34797],
       ['creta', 22671],
       ['sx4', 62000],
       ['xcent', 34000],
       ['jazz', 12000],
       ['amaze', 36054],
       ['Honda CB Shine', 53000],
       ['dzire', 77427],
       ['wagon r', 65000],
       ['corolla altis', 89000],
       ['amaze', 40026],
       ['i10', 57000],
       ['brio', 16500],
       ['i20', 58000],
       ['TVS Apache RTR 180', 23000],
       ['dzire', 45780],
       ['eon', 15000],
       ['TVS Apache RTR 160', 19000],
       ['Bajaj Pulsar 150', 60000],
       ['eon', 38488],
       ['brio', 53675],
       ['wagon r', 5200],
       ['KTM RC390', 21700],
       ['fortuner', 135000],
       ['Bajaj Avenger 220', 500],
       ['city', 48000],
       ['sx4', 43000],
       ['ciaz', 37000],
       ['corolla altis', 23000],
       ['grand i10', 3493],
       ['dzire', 45000],
       ['innova', 58242],
       ['innova', 15000],
       ['xcent', 35866],
       ['ertiga', 26000],
       ['etios liva', 47000],
       ['Hero Passion Pro', 1000],
       ['city', 60076],
       ['TVS Apache RTR 160', 11800],
       ['city', 34000],
       ['i20', 7000],
       ['innova', 90000],
       ['fortuner', 104707],
       ['Honda CB Unicorn', 38600],
       ['Hero Super Splendor', 55000],
       ['city', 9000],
       ['Honda CB twister', 32000],
       ['Hero Splender iSmart', 14000],
       ['etios g', 39485],
       ['ertiga', 25870],
       ['verna', 15141],
       ['brio', 31427],
       ['ignis', 2400],
       ['Bajaj Avenger Street 220', 24000],
       ['city', 24800],
       ['Bajaj Discover 125', 25000],
       ['city', 40324],
       ['Bajaj Pulsar 220 F', 24000],
       ['Honda CB Hornet 160R', 11000],
       ['Hero Passion X pro', 31000],
       ['fortuner', 50024],
       ['corolla altis', 56000],
       ['grand i10', 20114],
       ['Royal Enfield Thunder 350', 6900],
       ['brio', 5464],
       ['alto k10', 25000],
       ['Hero Glamour', 18000],
       ['corolla altis', 45000],
       ['Hyosung GT250R', 16500],
       ['city', 69341],
       ['KTM RC200', 4000]], dtype=object)

In [64]:
np.hstack((X_train[["Fuel_Type","Seller_Type"]].values,X_train_new)).shape

(240, 7)

### 4. OneHotEncoding with Top categories

In [91]:
counts=df["Car_Name"].value_counts()

In [93]:
df["Car_Name"].nunique()
threshold = 10

In [95]:
rep1=counts[counts <= threshold].index

In [98]:
pd.get_dummies(df["Car_Name"].replace(rep1,"uncommon"))

      city  corolla altis  fortuner  uncommon  verna
0    False          False     False      True  False
1    False          False     False      True  False
2    False          False     False      True  False
3    False          False     False      True  False
4    False          False     False      True  False
..     ...            ...       ...       ...    ...
296   True          False     False     False  False
297  False          False     False      True  False
298   True          False     False     False  False
299   True          False     False     False  False
300  False          False     False      True  False

[301 rows x 5 columns]