In [149]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [151]:
new=pd.read_csv("CustomerPurchase.csv")

In [153]:
new.head()

   Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [155]:
new.sample()

    Customer ID  Age  Gender Education Review Purchased
48         1069   39  Female        UG   Good       Yes

In [157]:
new.shape

(50, 6)

In [159]:
new.describe()

       Customer ID        Age
count     50.00000  50.000000
mean    1045.50000  54.160000
std       14.57738  25.658161
min     1021.00000  15.000000
25%     1033.25000  30.250000
50%     1045.50000  57.000000
75%     1057.75000  74.000000
max     1070.00000  98.000000

In [161]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  50 non-null     int64
 1   Age          50 non-null     int64
 2   Gender       50 non-null     object
 3   Education    50 non-null     object
 4   Review       50 non-null     object
 5   Purchased    50 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.5+ KB

In [163]:
new.duplicated().sum()

np.int64(0)

In [165]:
new.isnull().sum()

Customer ID    0
Age            0
Gender         0
Education      0
Review         0
Purchased      0
dtype: int64

In [168]:
new.tail()

    Customer ID  Age  Gender Education Review Purchased
45         1066   61    Male        PG   Poor       Yes
46         1067   64  Female        PG   Poor        No
47         1068   38  Female        PG   Good       Yes
48         1069   39  Female        UG   Good       Yes
49         1070   25  Female        UG   Good        No

In [169]:
from sklearn.model_selection import train_test_split

In [194]:
X_train, X_test, y_train, y_test = train_test_split(
    new[['Education', 'Review',]],
    new[['Customer ID', 'Age']],
    test_size=0.2,
    random_state=0
)

In [204]:
from sklearn.preprocessing import OrdinalEncoder

In [206]:
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

In [210]:
pd.DataFrame(X_train, columns=['Education', 'Review']).head()

   Education  Review
0        2.0     2.0
1        0.0     0.0
2        2.0     0.0
3        0.0     1.0
4        0.0     2.0